### ISSUE TITLE
Consider moving to AGPL license

### ISSUE THREAD

**Issue by dnaka91** [negue/meme-box#129]
Hello @negue, we talked already about this privately but here I just want to list up some reasons again why it might be good to move to the AGPL license for your project. In the end it's totally up to you. You can pick MIT, Apache-2.0 or whatever you like, after all it's your project and I just would like to give a recommendation.

So the biggest reason for GPL is that you shield yourself against companies using your project to make money without giving anything back to you or sharing their modifications with the community. If you for example pick MIT then anybody can mostly just do what they want with your project. That's is often nice for libraries as you want to make it as easy as possible for people to use your library and don't want legal issues to be in the way.

With GPL still everybody can use your project without any legal concerns. People can use it on their own stream, even if they make money. But if people fork your project and make many modifications, then this modifications must be public if given to other people. So if a big company would come along, take your code, make a product out of it that they sell, then they can't do that without breaking the license and you can technically sue them.

If some company come along and want to use your product that way, then they can still do that by acquiring an exclusive usage license that you can give out for free or sell to them. In a way they would support the project by paying for the license they buy from you.

I mentioned GPL instead of AGPL in the previous text as both licenses are almost indentical. The GPL has a loophole as it only covers software that is distributed as library or binary to the users but it doesn't cover websites or similar projects that are consumed by the browser or over the network. The AGPL covers this by adding the extra clause. Besides that it's identical to GPL.

I'm not a legal expert or anything, so please don't take my full word on this. This is my understanding of how the (A)GPL works and can be used.

Here are 2 recent articles about AGPL that made the round in several tech news:

- https://raymii.org/s/blog/I_enforced_the_AGPL_on_my_code_heres_how_it_went.html
- https://plausible.io/blog/open-source-licenses

**Comment by negue** [comment]
Hey @dnaka91 ,

sorry it took that much time, between working on memebox and reading into AGPL the time got lost some where.

The example were good and maybe even sparked some thoughts. But I have finally made the change here.

Meme-Box itself will be from now on `AGPL`.

Any helpers / utils will be extracted out to a `MIT` library, some of them already are at https://github.com/negue/gewd
