### ISSUE TITLE
Generic Ideas - Thread

### ISSUE THREAD

**Issue by negue** [negue/meme-box#135]
If you have an idea, feel free to post it here, and we can either all just "vote" by reacting with emote or discuss feature X here

**Comment by negue** [comment]
Text Media: - just using text or markdown

**Comment by negue** [comment]
In-App simple Image generator for example speech bubbles

**Comment by gigili** [comment]
Sending text information alongside media clips. When using twitch events would be good to be able to send a message such as X raided with N viewers along with the clip, or X cheered N bits so that it gets displayed on screen as well. But I guess that would be covered by Text Media suggestion.
