### ISSUE TITLE
Feature: Use wizard for add media dialog

### ISSUE THREAD

**Issue by owehmer** [negue/meme-box#242]
It would be nice to have a wizard guiding you through the add media process to make the whole process easier.

Like..
Step 1: Media Type
Step 2:  Name, general options (that are valid for multiple types)
Step 3: specifics

Maybe we only need two steps.

![image](https://user-images.githubusercontent.com/45573843/111695014-e5330300-8832-11eb-9c20-797a6ccea5c5.png)

**Comment by negue** [comment]
Closing this in favor of #292  (too many duplicate issues for this redesign / refactor)
