### ISSUE TITLE
Bug/Suggestion: Dragging an object in the assign media view

### ISSUE THREAD

**Issue by owehmer** [negue/meme-box#250]
If you drag for example a picture to the far right or left the picture will shrink. You can't drag it partially out of the screen like it is the case if you drag it up or down.

I think this should be unified, either every side can be out of bounds or none..?

**Comment by negue** [comment]
Thats probably because of https://www.npmjs.com/package/moveable which prevents that

So I dont know if its even possible to improve it

**Comment by owehmer** [comment]
Thats strange, but then you shouldn't  be able to drag in out on the top/bottom right? How does it know that there are boundaries to the left and right?

**Comment by negue** [comment]
Thats exactly the question :D - I'll take a look at it maybe tomorrow  maybe I can find something

**Comment by negue** [comment]
It seems to be now fixed? 

Maybe because of your refactor? I dunno - its fixed 🎉
