### ISSUE TITLE
Prevent switching between tabs when editing media  

### ISSUE THREAD

**Issue by gigili** [negue/meme-box#266]
When editing media prevent switching between Arrange and Preview tab if there are unsaved changes or warn the user that there are unsaved changes first. 

![capture](https://user-images.githubusercontent.com/2153382/114906494-61ad0780-9e1a-11eb-9bdc-9e14aadb903b.png)

**Comment by owehmer** [comment]
I'm currently working on improving the arrange view a little bit. I'll add a warning in that PR.

Thanks for the suggestion!
