### ISSUE TITLE
Selected media still visible after assign media was clicked

### ISSUE THREAD

**Issue by owehmer** [negue/meme-box#276]
If I select a media file and then click on the button to assign new media files, the rectangle is still visible.

![image](https://user-images.githubusercontent.com/45573843/116749897-e5ade480-aa01-11eb-8128-87ddc6cd30b1.png)

**Comment by negue** [comment]
Ohh I thought I fixed them all - I had to unselect that for example when you open the clip settings 

I'll fix it once your refactor  / improvements done

**Comment by owehmer** [comment]
Don't worry, I fixed at least two in my branch so far :) Just wanted to write that done so you have something for your patch notes
