### ISSUE TITLE
Custom Button Colors depending on the page?

### ISSUE THREAD

**Issue by negue** [negue/meme-box#28]
Now that there is material css vars added, we could have custom button colors per page :)

@whitep4nth3r what do you think ?

**Comment by whitep4nth3r** [comment]
I was actually trying to colour the buttons according to their action as a UX consistency - so purple was for edit, pink was for delete etc --- I don't want to add too many colours as it might run the risk of colour overload. Thoughts?

**Comment by negue** [comment]
I just thought it may look better to have one color per page :D - but yeah then it may be too many colors that way.

Closing this idea ^^
