### ISSUE TITLE
New type: iframe

### ISSUE THREAD

**Issue by negue** [negue/meme-box#32]

**Comment by ageddesi** [comment]
For the iframe, this would be on the add media section and also what options would you like.
iframe URL,
visible screen time.

do you need size the iframe?

**Comment by negue** [comment]
Oh do you want to work on it? :O  If not thats ok as well :D Had to write the notes down anyway :)

This would have to be done:

Where it would have to be added:
- [ ] add the enum, and maybe all other places where MediaType is used
- [ ] add to "add media" dialog
- [ ] add to the screen - media assignment dialog - filter 
- [ ] add to the targetscreen

As for the settings:
- [ ] only the URL  (which is already available, so just re-use the current one, which all other types already use)


Nearly "everything" (as of today) else is handled by the screen/media dialog which has the sizes / positions :)

**Comment by ageddesi** [comment]
Awesome, I will give it a shot today :)

**Comment by ageddesi** [comment]
@negue Thank you for the pull-request feedback I will get those changes modified for you.
