### ISSUE TITLE
Should not have unused variables

### ISSUE THREAD

**Issue by divshacker** [negue/meme-box#338]
Found variables that are declared but not used anywhere.

Variables that are declared and not used anywhere in the code are most likely an error due to incomplete refactoring. Such variables take up space in the code and can lead to confusion by readers.

Also, having unused variables affects the performances as well.
https://deepsource.io/gh/negue/meme-box/issue/JS-0128/occurrences

**Comment by divshacker** [comment]
May I work on this Please ?

**Comment by negue** [comment]
Hey, 

guess I forgot some places there haha - I think its time to enable more lints for that as well. But thats not the topic right now, unless you could also add this as a lint rule ? :) If not no worries, I'll just do it after most places have been fixed.

I think some of the folders you can ignore, for example the files in `memebox-streamdeck`  some of the code is not from me and there it might be nice to know which possible values the methods can get.

On Files like in the server / app (`src` ) / shared `projects` I think there it should be fine to remove them. On those you can delete the unused ones.

Yes feel free to work on it :) - Thanks for contributing

**Comment by divshacker** [comment]
Ok well I will make a PR and commit some changes.
