### ISSUE TITLE
First screen for new instances

### ISSUE THREAD

**Issue by gigili** [negue/meme-box#381]
When starting the MemeBox for the first time it used to show the `Getting started card` which guided the user as to what to do first before adding new actions. With the new view layout that gets hidden. 

If you switch the layout option than the old card shows up. Maybe we should consider either bringing that getting started card back to the new default layout view or have a whole new getting started screen for the new instances. 

The problem with the current (new) layout is that it is suggesting that you can add media as soon as you start the app for the first time, where as you actually have to at least setup the media folder first. 

Currently the default view shows: 
![memebox-first-start](https://user-images.githubusercontent.com/2153382/149518465-983cc814-d140-4a3b-b2b2-ccb51c90afe3.jpg)

And if you switch the layout option it shows:
![memebox-first-start-old-layout](https://user-images.githubusercontent.com/2153382/149518561-8bd12572-b5b2-4330-b2f8-968ed38a0941.jpg)

MemeBox version:
nightly20220114  (headless.exe) 

OS:
Windows 10

Browser:
Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by negue** [comment]
Yeah this definitely needs to be updated

**Comment by negue** [comment]
The newest (nightly) "Getting Started" Page should be way easier to understand now
