### ISSUE TITLE
screens don't auto-connect to OBS if memebox is started when OBS is already running

### ISSUE THREAD

**Issue by matthewbrandt** [negue/meme-box#450]
current workaround: start memebox before OBS

system: MacOS Monterey 12.3.1, MacBook Pro 16" 2020 (Intel)

**Comment by negue** [comment]
The next nightly version: On Startup now Memebox will refresh all screens added in obs.  :)  

That should fix these connection issues :>

**Comment by negue** [comment]
Seems I need to re-do it and keep waiting until the OBS Connection opens up
