### ISSUE TITLE
Screen Item Config: Add a placeholder for Animation Duration

### ISSUE THREAD

**Issue by negue** [negue/meme-box#517]
The default duration is 777ms so this value probably should be added there as a placeholder

![grafik](https://user-images.githubusercontent.com/842273/193480266-cb5de4d7-22a6-48b5-8a1b-3c32fbd4dfb7.png)

**Comment by khalatevarun** [comment]
Could you please review the PR.

**Comment by negue** [comment]
@all-contributors please add @khalatevarun for code
