### ISSUE TITLE
Issue in: Filters (search bar)

### ISSUE THREAD

**Issue by mogurimogu** [negue/meme-box#534]
I can't write a space with spacebar in search bar, filter opens and closes all time.

### Version:
> 2022.1 - b66ee71

**Comment by negue** [comment]
Wow - you are right, seems that the key-down event triggered the expansion panel - good catch haha

This will be fixed in the new release - which I hope to do this week :)

Thank you for reporting that 👍

**Comment by mogurimogu** [comment]
Thanks to you! meme-box is amazing 👍

**Comment by negue** [comment]
Thank you ❤️ 

Released a new Version now :) please try again.

Also if you don't mind would you tell me your Twitch Channel? Also interesting to see what you created / use with it ^^
