### ISSUE TITLE
Twitch events - validation

### ISSUE THREAD

**Issue by gigili** [negue/meme-box#66]
There should be some validation added to the form when adding new events so that warn or prevent the event to be saved that has the same command twice.

Example:

add:
name: event #1 
event: message
meme: img
contains: !wow

Expected outcome: This should save the event 

try to add again:
name: event #1 
event: message
meme: img
contains: !wow

Expected outcome: This should show an error that the event with the command !wow already exists. 
Additional suggestions: Offer to either save the event with the same command as well or change the command to something else, as someone might want to trigger more than one event with a single command

**Comment by negue** [comment]
It may be a feature not a bug - maybe someone wants to trigger multiple clips with one command, maybe all with a different timeout or something 


And since it will "a feature" I don't know how to "catch" that there :/

**Comment by gigili** [comment]
That is why I wrote 

> Additional suggestions: Offer to either save the event with the same command as well or change the command to something else, as someone might want to trigger more than one event with a single command

So jut show a confirmation dialog to the user if they try to save an event with an exists command and maybe have an option to like click on the checkbox that says "Don't warn me about this again?".

Just in case someone really didn't know they were already using a command, because that might be useful for people who have a ton of commands added.
