### ISSUE TITLE
Media folder path can't have / at the end

### ISSUE THREAD

**Issue by gigili** [negue/meme-box#95]
When entering your media folder path on the setting screen you can't have / (forward slash) at the end of the path as it breaks the apps url generation.

Example:

/home/gigili/Downloads - will work as a media path and any selected media will show up
/home/gigili/Downloads/ - will not work and any selected media will appear to have a missing / slash in the generated url

My suggestion for this fix is to implement rtrim method ( [PHP example](https://www.php.net/manual/en/function.rtrim.php) | [JS Example](https://github.com/gigili/good-food-tracker-api/blob/master/helpers/utilities.ts#L82) ) which would remove any / at the end of the media path on update button click before storing that value.

OS: Linux | Manjaro

**Comment by negue** [comment]
@all-contributors please add @gigili for bug and ideas
